# -*- coding: utf-8 -*-
"""
/***************************************************************************
Quick VRT Imagery Loader
Plugin for searching and loading satellite imagery via the Microsoft Planetary Computer STAC API. 
It lists pre-configured compositions and loads images as VRT. 
Supports Sentinel-2 and Landsat collections with multiple band compositions
(True Color, False Color NIR/SWIR, Agriculture, Geology, Urban, Bathymetric, and more).
Compatible with QGIS 3.x (Qt5) and QGIS 4.x (Qt6).

 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-02-01
        copyright            : (C) 2026 by Vagner Teixeira
        email                : junior.vagner@live.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

# -*- coding: utf-8 -*-

def classFactory(iface):
    from .sentinel_stac_loader import SentinelSTAC
    return SentinelSTAC(iface)