# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SentinelSTACDialog
                                 A QGIS plugin
 Loads Sentinel-2 Microsoft's Planetary Computer STAC API
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-02-01
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Vagner Teixeira
        email                : junior.vagner@live.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
import pystac_client
import planetary_computer
import shapely.geometry
from qgis.core import (
    QgsRasterLayer, QgsProject, QgsCoordinateTransform, 
    QgsCoordinateReferenceSystem, QgsMessageLog, Qgis
)
from qgis.utils import iface
import processing

# CONFIGURE AQUI O CÓDIGO PARA DOWNLOAD
# Opções de composição: 
#"True Color", "False Color (NIR)", "False Color (SWIR)",
#Agriculture", "Geology", "Shortwave Infrared", "Bathymetric", "Vegetation Index"

data_inicio = "2025-07-08"
data_final = "2025-08-31"
composicao = "Vegetation Index"
indice = 0


# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer

FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'sentinel_stac_loader_dialog_base.ui'))


class SentinelSTACDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(SentinelSTACDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)



class SentinelSTACLoader:
    def __init__(self):
        self.catalog_url = "https://planetarycomputer.microsoft.com/api/stac/v1"
        self.collection = "sentinel-2-l2a"
        
        # Dicionário expandido de composições
        # Sentinel-2 Bands: B02(B), B03(G), B04(R), B08(NIR), B11(SWIR1), B12(SWIR2)
        self.compositions = {
            "True Color": ['B04', 'B03', 'B02'],             # Cor Real
            "False Color (NIR)": ['B08', 'B04', 'B03'],      # Vegetação (Infravermelho Próximo)
            "False Color (SWIR)": ['B12', 'B08', 'B04'],     # Vegetação/Solo (Infravermelho Ondas Curtas)
            "Agriculture": ['B11', 'B08', 'B02'],            # Culturas agrícolas
            "Geology": ['B12', 'B11', 'B02'],                # Geologia e Solo
            "Bathymetric": ['B04', ',B03', 'B01'],           # Água e sedimentos
            "Vegetation Index": ['B08', 'B11', 'B04'],       # Densidade de biomassa
            "Shortwave Infrared": ['B12', 'B08', 'B03']      # Áreas queimadas e fumaça
        }

    def get_canvas_bbox(self):
        """Obtém a extensão atual do canvas em WGS84."""
        canvas = iface.mapCanvas()
        extent = canvas.extent()
        crs_src = canvas.mapSettings().destinationCrs()
        crs_dest = QgsCoordinateReferenceSystem("EPSG:4326")
        
        xform = QgsCoordinateTransform(crs_src, crs_dest, QgsProject.instance())
        
        p1 = xform.transform(extent.xMinimum(), extent.yMinimum())
        p2 = xform.transform(extent.xMaximum(), extent.yMaximum())
        
        return [p1.x(), p1.y(), p2.x(), p2.y()]

    def search_images(self, bbox, start_date, end_date):
        """Conecta ao STAC e busca os itens ordenados por nuvens."""
        try:
            catalog = pystac_client.Client.open(
                self.catalog_url
            )

            search = catalog.search(
                collections=[self.collection],
                bbox=bbox,
                datetime=f"{start_date}/{end_date}"
            )
            
            items = list(search.get_all_items())
            # Ordena: a primeira da lista é a que tem menos nuvens
            return sorted(items, key=lambda x: x.properties.get("eo:cloud_cover", 100))
        except Exception as e:
            self.show_message("Erro na busca STAC", str(e), Qgis.Critical)
            return []

    def list_available_images(self, start_date, end_date):
        """Lista as imagens encontradas no console para ajudar na escolha do índice."""
        bbox = self.get_canvas_bbox()
        items = self.search_images(bbox, start_date, end_date)

        if not items:
            print("Nenhuma imagem encontrada para listar.")
            return

        print(f"\n--- IMAGENS ENCONTRADAS NO PERÍODO ({len(items)}) ---")
        print(f"{'ÍNDICE':<8} | {'DATA':<20} | {'NUVENS (%)':<10} | {'ID'}")
        print("-" * 70)

        for idx, item in enumerate(items):
            date_str = item.properties.get("datetime", "N/A")
            clouds = item.properties.get("eo:cloud_cover", 0)
            img_id = item.id
            print(f"{idx:<8} | {date_str:<20} | {clouds:<10.2f} | {img_id}")
        
        print("-" * 70)
        self.show_message("Lista Gerada", f"Foram encontradas {len(items)} imagens. Veja o console Python.", Qgis.Info)

    def load_vrt(self, item, composition_name):
        """Gera o VRT baseado na composição escolhida."""
        bands = self.compositions.get(composition_name)
        band_hrefs = []
        
        for band in bands:
            asset = item.assets.get(band)
            if asset:
                signed_href = planetary_computer.sign(asset.href)
                band_hrefs.append(f"/vsicurl/{signed_href}")

        if not band_hrefs:
            return False

        params = {
            'INPUT': band_hrefs,
            'SEPARATE': True,
            'OUTPUT': 'TEMPORARY_OUTPUT'
        }

        try:
            result = processing.run("gdal:buildvirtualraster", params)
            cloud_pct = item.properties.get("eo:cloud_cover", 0)
            layer_name = f"S2_{item.id}_{composition_name} ({cloud_pct:.1f}% Nuvens)"
            
            vrt_layer = QgsRasterLayer(result['OUTPUT'], layer_name)
            
            if vrt_layer.isValid():
                QgsProject.instance().addMapLayer(vrt_layer)
                return True
        except Exception as e:
            self.show_message("Erro ao processar VRT", str(e), Qgis.Critical)
        
        return False

    def show_message(self, title, message, level=Qgis.Info):
        """Feedback na barra superior do QGIS."""
        iface.messageBar().pushMessage(title, message, level, 5)

    def run(self, start_date, end_date, composition="True Color", image_index=0):
        """
        Método principal.
        image_index: 0 para a imagem com menos nuvens, 1 para a segunda melhor, etc.
        """
        bbox = self.get_canvas_bbox()
        items = self.search_images(bbox, start_date, end_date)

        if not items:
            self.show_message("STAC", "Nenhuma imagem encontrada.", Qgis.Warning)
            return

        # Verifica se o índice solicitado existe na lista
        if image_index >= len(items):
            self.show_message("STAC", f"Índice {image_index} fora de alcance. Máximo: {len(items)-1}", Qgis.Warning)
            image_index = 0

        selected_item = items[image_index]
        cloud_pct = selected_item.properties.get("eo:cloud_cover", 100)
        
        self.show_message("STAC", f"Carregando a {image_index + 1}ª melhor imagem ({cloud_pct:.2f}% nuvens)")
        
        success = self.load_vrt(selected_item, composition)
        if success:
            self.show_message("Sucesso", f"Composição {composition} carregada!", Qgis.Success)


loader = SentinelSTACLoader()

loader.list_available_images(data_inicio, data_final)

loader.run(
    start_date=data_inicio, 
    end_date=data_final, 
    composition=composicao, 
    image_index=indice 
)