# -*- coding: utf-8 -*-
"""
/***************************************************************************
    Quick VRT Imagery Loader
    A QGIS plugin
 Loads satellite imagery from Microsoft's Planetary Computer STAC API
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-02-01
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Vagner Teixeira
        email                : junior.vagner@live.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os.path

# 1. Imports padrão do QGIS e Qt (Seguros: não dependem de libs externas)
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction
from qgis.core import Qgis, QgsMessageLog

# 2. Import do seu gerenciador (Certifique-se que o manager NÃO importa pystac no topo dele)
from .dependency_manager import DependencyManager

# OBS: NUNCA importe o SentinelSTACDialog aqui no topo.
# Isso causaria o erro de importação no Windows assim que o QGIS abrisse.

class SentinelSTAC:
    """Implementação do Plugin QGIS."""

    def __init__(self, iface):
        """Construtor."""
        self.iface = iface
        
        # Mapeamento correto: 'nome-no-pip': 'modulo_para_import'
        self.deps = {
            'pystac-client': 'pystac_client',
            'planetary-computer': 'planetary_computer',
            'shapely': 'shapely'
        }
        
        self.dep_manager = DependencyManager(self.iface, "Quick VRT Imagery Loader", self.deps)
        self.plugin_dir = os.path.dirname(__file__)
        self.dlg = None 
        
        # Tradução
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'SentinelSTAC_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)
            
        self.actions = []
        self.menu = self.tr(u'&Quick VRT Imagery Loader')

    def tr(self, message):
        """API de tradução do Qt."""
        return QCoreApplication.translate('SentinelSTAC', message)

    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        parent=None):
        """Adiciona uma ação à barra de ferramentas e menu."""

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip:
            action.setStatusTip(status_tip)

        if add_to_toolbar:
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(self.menu, action)

        self.actions.append(action)
        return action

    def initGui(self):
        """Inicializa a interface do plugin no QGIS."""
        
        # Verifica dependências no início
        # No Windows, isso abrirá o diálogo se algo faltar
        self.dependencies_ok = self.dep_manager.check_and_install()
        
        icon_path = os.path.join(self.plugin_dir, 'icon.png') # Ajuste se usar resources
        
        self.main_action = self.add_action(
            icon_path,
            text=self.tr(u'Abrir Sentinel STAC Loader'),
            callback=self.run,
            enabled_flag=self.dependencies_ok, # Desativa o botão se não houver deps
            parent=self.iface.mainWindow())

        if not self.dependencies_ok:
            self.iface.messageBar().pushMessage(
                "Atenção", 
                "Dependências ausentes. Clique no ícone do plugin para tentar instalar novamente.", 
                level=Qgis.Warning,
                duration=5
            )

    def unload(self):
        """Remove o plugin do QGIS."""
        for action in self.actions:
            self.iface.removePluginMenu(self.menu, action)
            self.iface.removeToolBarIcon(action)

    def run(self):
        """Executa a lógica principal do plugin."""
        
        # Re-checa antes de rodar (caso o usuário tenha tentado instalar e falhado)
        if not self.dep_manager.check_and_install():
            return

        # --- LAZY IMPORT (Importação Tardia) ---
        # Só importamos o Dialog aqui dentro para evitar que o erro 
        # de importação aconteça no carregamento do QGIS.
        from .sentinel_stac_loader_dialog import SentinelSTACDialog
        
        if self.dlg is None:
            self.dlg = SentinelSTACDialog()
            # Conexão de sinais dos botões do seu .ui
            # Certifique-se que esses nomes batem com o seu Qt Designer
            if hasattr(self.dlg, 'btn_carregar'):
                self.dlg.btn_carregar.clicked.connect(self.dlg.process_stac_load)
            if hasattr(self.dlg, 'btn_listar'):
                self.dlg.btn_listar.clicked.connect(self.dlg.popular_tabela)

        self.dlg.show()
        self.dlg.exec_()